import { Injectable } from '@nestjs/common'
import { PrismaService } from 'src/prisma/prisma.service'

@Injectable()
export class DashboardRepository {
  constructor(private prisma: PrismaService) { }

  // 获取平台统计汇总
  async summary() {
    const [
      orderCount,
      storeServiceOrderCount,
      productTotal,
      storeTotal,
      applyingWithdrawCount,
      tobProductCount,
      tocProductCount,
      vipPlanCount,
      categoryCount,
      stockTemplateCount,
      phoneModelCount,
      tocOrderCount,
      managerOrderCount,
      pendingCount,
      paidCount,
      shippedCount,
      completedCount,
      cancelledCount,
      processingCount,
      refundedCount,
      normalUserCount,
      vipUserCount,
      managerUserCount,
      activeAccountCount,
      inactiveAccountCount,
      boundManagerStoreCount,
      storeMemberCount,
      settlementRecordCount,
      pendingSettlementCount,
      settledCount,
      paidWithdrawCount,
      pendingSettlementAmount,
      withdrawAmount,
      platformFeeAmount,
      managerIncomeAmount,
    ] = await this.prisma.$transaction([
      this.prisma.order.count(),
      this.prisma.storeServiceOrder.count(),
      this.prisma.product.count(),
      this.prisma.store.count(),
      this.prisma.walletWithdrawApply.count({ where: { status: 'APPLYING' } }),
      this.prisma.product.count({ where: { target: 'TOB' } }),
      this.prisma.product.count({ where: { target: 'TOC' } }),
      this.prisma.vipPlan.count(),
      this.prisma.category.count(),
      this.prisma.stockModel.count(),
      this.prisma.phoneModel.count(),
      this.prisma.order.count({ where: { target: 'TOC' } }),
      this.prisma.order.count({ where: { target: 'TOB' } }),
      this.prisma.order.count({ where: { status: 'PENDING' } }),
      this.prisma.order.count({ where: { status: 'PAID' } }),
      this.prisma.order.count({ where: { status: 'SHIPPED' } }),
      this.prisma.order.count({ where: { status: 'COMPLETED' } }),
      this.prisma.order.count({ where: { status: 'CANCELLED' } }),
      this.prisma.order.count({ where: { status: 'PROCESSING' } }),
      this.prisma.order.count({ where: { status: 'REFUNDED' } }),
      this.prisma.user.count({ where: { role: 'USER' } }),
      this.prisma.user.count({ where: { role: 'VIP' } }),
      this.prisma.user.count({ where: { role: 'MANAGER' } }),
      this.prisma.user.count({ where: { status: 'ACTIVE' } }),
      this.prisma.user.count({ where: { status: 'INACTIVE' } }),
      this.prisma.store.count({ where: { managerId: { not: null } } }),
      this.prisma.user.count({ where: { storeId: { not: null }, role: { not: 'MANAGER' } } }),
      this.prisma.settlementRecord.count(),
      this.prisma.settlementRecord.count({ where: { status: 'PENDING' } }),
      this.prisma.settlementRecord.count({ where: { status: 'SETTLED' } }),
      this.prisma.walletWithdrawApply.count({ where: { status: 'PAID' } }),
      this.prisma.settlementRecord.aggregate({
        where: { status: 'PENDING' },
        _sum: { managerIncome: true },
      }),
      this.prisma.walletWithdrawApply.aggregate({
        where: { status: 'PAID' },
        _sum: { amount: true },
      }),
      this.prisma.settlementRecord.aggregate({
        _sum: { platformFee: true },
      }),
      this.prisma.settlementRecord.aggregate({
        _sum: { managerIncome: true },
      }),
    ])

    return {
      orderTotal: orderCount + storeServiceOrderCount,
      storeServiceOrderCount,
      productTotal,
      storeTotal,
      applyingWithdrawCount,
      tobProductCount,
      tocProductCount,
      vipPlanCount,
      categoryCount,
      stockTemplateCount,
      phoneModelCount,
      tocOrderCount,
      managerOrderCount,
      pendingCount,
      paidCount,
      shippedCount,
      completedCount,
      cancelledCount,
      processingCount,
      refundedCount,
      normalUserCount,
      vipUserCount,
      managerUserCount,
      activeAccountCount,
      inactiveAccountCount,
      boundManagerStoreCount,
      storeMemberCount,
      settlementRecordCount,
      pendingSettlementCount,
      settledCount,
      paidWithdrawCount,
      pendingSettlementAmount: Number(pendingSettlementAmount._sum.managerIncome ?? 0),
      withdrawAmount: Number(withdrawAmount._sum.amount ?? 0),
      platformFeeAmount: Number(platformFeeAmount._sum.platformFee ?? 0),
      managerIncomeAmount: Number(managerIncomeAmount._sum.managerIncome ?? 0),
    }
  }
}
